#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x90A8763631A6CB60 (tw-public@gmx.de)
#
Name     : XStatic
Version  : 1.0.1
Release  : 17
URL      : http://pypi.debian.net/XStatic/XStatic-1.0.1.tar.gz
Source0  : http://pypi.debian.net/XStatic/XStatic-1.0.1.tar.gz
Source99 : https://pypi.python.org/packages/source/X/XStatic/XStatic-1.0.1.tar.gz.asc
Summary  : XStatic base package with minimal support code
Group    : Development/Tools
License  : MIT
Requires: XStatic-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
-------
        
        The goal of XStatic family of packages is to provide static file packages
        with minimal overhead - without selling you some dependencies you don't want.
        
        XStatic has some minimal support code for working with the XStatic-* packages.

%package python
Summary: python components for the XStatic package.
Group: Default
Provides: xstatic-python

%description python
python components for the XStatic package.


%prep
%setup -q -n XStatic-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503083638
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503083638
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
