#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x90A8763631A6CB60 (tw-public@gmx.de)
#
Name     : XStatic
Version  : 1.0.1
Release  : 22
URL      : https://files.pythonhosted.org/packages/3e/30/726b61d07abd031b32db956adfbcf8924687e07879c1b63b777855c75289/XStatic-1.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/3e/30/726b61d07abd031b32db956adfbcf8924687e07879c1b63b777855c75289/XStatic-1.0.1.tar.gz
Source99 : https://files.pythonhosted.org/packages/3e/30/726b61d07abd031b32db956adfbcf8924687e07879c1b63b777855c75289/XStatic-1.0.1.tar.gz.asc
Summary  : XStatic base package with minimal support code
Group    : Development/Tools
License  : MIT
Requires: XStatic-python3
Requires: XStatic-python
BuildRequires : buildreq-distutils3

%description
-------
        
        The goal of XStatic family of packages is to provide static file packages
        with minimal overhead - without selling you some dependencies you don't want.
        
        XStatic has some minimal support code for working with the XStatic-* packages.

%package python
Summary: python components for the XStatic package.
Group: Default
Requires: XStatic-python3
Provides: xstatic-python

%description python
python components for the XStatic package.


%package python3
Summary: python3 components for the XStatic package.
Group: Default
Requires: python3-core

%description python3
python3 components for the XStatic package.


%prep
%setup -q -n XStatic-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533945756
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
